### PR TITLE
Fix Subscriber staying paused after releasing messages

### LINKED ISSUE #4152: Pub/Sub Subscriber halts and never resumes
```rb
=> #<Google::Cloud::PubSub::Subscriber::Stream (inventory: 0, status: sleep)>
[93] pry(main)> g.send :unpause_streaming?
=> true
[94] pry(main)> g.instance_variable_get("@paused")
=> true
```

Stays in this state.

### PR DESCRIPTION
**Pull request by blowmage**
* Correctly reset the `Subscriber` state when releasing messages after the callback either raises an error, or the callback fails to call `acknowledge` or `modify_ack_deadline` on the message. If a `Subscriber` fills it's inventory, and stops pulling additional messages (pauses), before all the callbacks are completed then the `Subscriber` could become stuck in a paused state.
* A paused `Subscriber` will now check whether to unpause after the callback is completed, instead of when `acknowledge` or `modify_ack_deadline` is called on the message.

[fixes #4152]

### CODE REVIEW

File: google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb [hunk 1]
```diff
@@ -138,12 +137,27 @@ def modify_ack_deadline deadline, *messages
...
+            ack_ids = coerce_ack_ids messages
+            return if ack_ids.empty?
+
+            synchronize do
+              # Remove from inventory if the message was not explicitly acked or
+              # nacked in the callback
+              @inventory.remove ack_ids
+              # Check whether to unpause the stream only after the callback is
+              # completed and the thread is being reclaimed.
+              unpause_streaming!
```
Comment (ce07c3) [inline google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb]: Do we need to check inventory fill levels before resuming? When the halts occurred I tried to call unpause strraming but it wouldn’t resume. I’ll try this PR out.

**Comment by ce07c3** [comment]
Seems fixed!
