### PR TITLE
docs(bigtable): Fix timestamp param documentation

### LINKED ISSUE #3676: Cloud Bigtable setCell timestamp field does not set timestamp on cell.
When setting the timestamp on a cell value, the timestamp is ignored. You can test this with the [hello world](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/bigtable/hello_world.rb) 

```
  entry = table.new_mutation_entry "greeting#{i}"
  entry.set_cell(
    column_family,
    column_qualifier,
    value,
    timestamp: Time.now.to_i * 1000
  )

  table.mutate_row entry
```
When I read the results, this is what I see: 
```
greeting0
  cf:greeting                              @ 1970/01/18-21:16:13.999000
    "Hello World!"
----------------------------------------
greeting1
  cf:greeting                              @ 1970/01/18-21:16:14.000000
    "Hello Bigtable!"
----------------------------------------
greeting2
  cf:greeting                              @ 1970/01/18-21:16:14.000000
    "Hello Ruby!"
```

### PR DESCRIPTION
**Pull request by quartzmo**
* Add tests demonstrating correct and incorrect timestamp arguments.
* Add param documentation to clarify that values are in microseconds but must match the granularity of the table, which is currently always milliseconds, meaning that the microsecond values must be rounded to the nearest `1000`.
* Remove `Time` type from `timestamp` parameter types list, since its use raises an error.

[closes #3676]

### CODE REVIEW

**Comment by blowmage** [comment]
Removing `Time` from the documentation makes the documentation reflect the current implementation. Another option is to add support for `Time` objects to the implementation and make it match the documentation. I slightly prefer the latter, but I'm okay with the former (and the PR as it is now) if an argument can be made against supporting `Time`.

**Comment by quartzmo** [comment]
Yes, given the current service behavior (see tests) I'd rather force the user to supply their own microsecond integers rounded to the nearest millisecond.

**Comment by blowmage** [comment]
After an offline discussion I see an argument to correct the docs. We have several code examples in comments that direct users to set the timestamp value to milliseconds instead of microseconds with millisecond granularity. All those instances should also be updated in this PR.

**Comment by quartzmo** [comment]
@blowmage Great catch on the code examples! I'll update them to microseconds values right away.

**Comment by quartzmo** [comment]
@blowmage Updated code examples and unit test fixtures.

File: google-cloud-bigtable/test/helper.rb [hunk 1]
```diff
@@ -259,3 +259,8 @@ def read_rows_acceptance_test_data
 
   tests
 end
+
+# A microseconds integer rounded to the nearest millisecond. For example: `1564257960168000`.
+def timestamp_micros
```
Comment (blowmage) [inline google-cloud-bigtable/test/helper.rb]: I think this method should be in the helper class, not on main.

Comment (quartzmo) [reply google-cloud-bigtable/test/helper.rb]: Thanks, moved.

File: google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb [hunk 2]
```diff
@@ -74,6 +74,89 @@
...
+    end.must_raise Google::Protobuf::TypeError
+    err.message.must_match "Expected number type for integral field 'timestamp_micros' (given Time)."
+  end
+
+  it "raises when set_cell with incorrect microsecond integer timestamp" do
+    postfix = random_str
+    row_key = "setcell-#{postfix}"
+    qualifier = "mutate-row-#{postfix}"
+    t = Time.now
+    timestamp_micros = t.to_i * 1000000 + t.usec
```
Comment (blowmage) [inline google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb]: We have a 1 in 1000 chance of `` ending in `000` and this test failing. Perhaps add a check for this here?

```suggestion
    timestamp_micros = (Time.now.to_f * 1000000).round
    timestamp_micros += 1 if (timestamp_micros % 10).zero?
```

File: google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb [hunk 3]
```diff
@@ -74,6 +74,89 @@
...
+      table.mutate_row(entry)
+    end.must_raise Google::Gax::RetryError
+    err.message.must_match /Timestamp granularity mismatch. Expected a multiple of 1000 \(millisecond granularity\), but got #{timestamp_micros}/
+  end
+
+  it "raises when set_cell with incorrect millisecond integer timestamp" do
+    postfix = random_str
+    row_key = "setcell-#{postfix}"
+    qualifier = "mutate-row-#{postfix}"
+    t = Time.now
```
Comment (blowmage) [inline google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb]: This line isn't needed anymore.

File: google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb [hunk 4]
```diff
@@ -74,6 +74,88 @@
...
+      table.mutate_row(entry)
+    end.must_raise Google::Gax::RetryError
+    err.message.must_match /Timestamp granularity mismatch. Expected a multiple of 1000 \(millisecond granularity\), but got #{timestamp_micros}/
+  end
+
+  it "raises when set_cell with incorrect millisecond integer timestamp" do
+    postfix = random_str
+    row_key = "setcell-#{postfix}"
+    qualifier = "mutate-row-#{postfix}"
+    timestamp_millis = (Time.now.to_f * 1000).to_i
```
Comment (blowmage) [inline google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb]: I think this test also has a 1 in 1000 chance of not raising.

```suggestion
    timestamp_millis = (Time.now.to_f * 1000).round
    timestamp_millis += 1 if (timestamp_millis % 10).zero?
```
