### PR TITLE
fix: add error_codes for google cloud errors

### LINKED ISSUE #20534: Add GRPC error code to Ruby Cloud error classes for the REST wrapping cases.
Currently the Ruby Cloud errors surface the underlying cause's error code. When they wrap HTTP error there is no `code` (there is an http status code in `status_code`). We should add the corresponding GRPC error code directly to the classes.

### PR DESCRIPTION
**Pull request by viacheslav-rostovtsev**
closes #20534

### CODE REVIEW

**Comment by dazuma** [comment]
Seems we're overriding the method for all the subclasses. Under what circumstance is the base class's method called?

**Comment by viacheslav-rostovtsev** [comment]
We instantiate base class if we can't find a correct subclass: https://github.com/googleapis/google-cloud-ruby/blob/74b429a39e014e01dd06b6a01dbd1f6847657d9e/google-cloud-errors/lib/google/cloud/errors.rb#L227
e.g. any unmatched HTTP error code will lead to that.

File: google-cloud-errors/lib/google/cloud/errors.rb [hunk 1]
```diff
@@ -231,6 +231,13 @@ def self.gapi_error_class_for http_status_code
     ##
     # Canceled indicates the operation was cancelled (typically by the caller).
     class CanceledError < Error
+      ##
+      # gRPC error code for CANCELLED
+      #
+      # @return [Int]
```
Comment (dazuma) [inline google-cloud-errors/lib/google/cloud/errors.rb:237]: The type is `Integer`. Here and below.

**Review by dazuma — APPROVED** [review]

**Comment by dazuma** [comment]
If you rebase or merge the latest main, it should resolve the missing checks. (I just added Ruby 3.2.)

File: google-cloud-errors/lib/google/cloud/errors.rb (hunk 1 above)
Comment (viacheslav-rostovtsev) [reply google-cloud-errors/lib/google/cloud/errors.rb]: :+1:

File: google-cloud-errors/lib/google/cloud/errors.rb [hunk 2]
```diff
@@ -231,6 +231,13 @@ def self.gapi_error_class_for http_status_code
     ##
     # Canceled indicates the operation was cancelled (typically by the caller).
     class CanceledError < Error
+      ##
+      # gRPC error code for CANCELLED
+      #
+      # @return [Integer]
+      def code
+        1
```
Comment (shivgautam) [inline google-cloud-errors/lib/google/cloud/errors.rb:239]: Should we define constants like Error::CanceledError = 1 and then use the constant here as return value? This way all constants can be declared in one place. It can help with tests too, instead of checking individual values
