### PR TITLE
Fix remaining Logging documentation warnings

### LINKED ISSUE #2308: Logging Documentation warnings
We get the following warnings when generating the documentation. Most of them look to be due to use of a generic templating syntax that needs to be escaped. For example, consider the following documentation:

```ruby
# @param name [String]
#   The data source in the form:
#   +projects/{project_id}/dataSources/{data_source_id}+
```

The text `"{project_id}"` is a YARD directive. To be valid YARD documentation it needs to be escaped, as `"\{project_id}"`.

It also has a couple warnings for documenting a parameter name that doesn't exist.

Here are the warnings:

```
[warn]: @param tag has unknown parameter name: *kwargs 
    in file `lib/google/cloud/logging/middleware.rb' near line 54
[warn]: @param tag has unknown parameter name: timeout 
    in file `lib/google/cloud/logging/async_writer.rb' near line 293
[warn]: In file `lib/google/cloud/logging/rails.rb':32: Cannot resolve link to use_logging? from text:
	{use_logging?}...
[warn]: In file `lib/google/cloud/logging/logger.rb':21: Cannot resolve link to #write_entries from text:
	...{#write_entries}...
[warn]: In file `lib/google/cloud/logging/logger.rb':66: Cannot resolve link to #write_entries from text:
	...{#write_entries}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/api/metric.rb':68: Cannot resolve link to requests from text:
	...{requests}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/api/metric.rb':68: Cannot resolve link to transmitted from text:
	...{transmitted}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/api/metric.rb':68: Cannot resolve link to requests from text:
	...{requests}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/api/metric.rb':68: Cannot resolve link to transmitted from text:
	...{transmitted}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to year from text:
	...{year}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to month from text:
	...{month}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to day from text:
	...{day}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to hour from text:
	...{hour}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to min from text:
	...{min}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to sec from text:
	...{sec}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to frac_sec from text:
	...{frac_sec}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to year from text:
	...{year}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to month from text:
	...{month}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to day from text:
	...{day}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to hour from text:
	...{hour}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to min from text:
	...{min}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb':79: Cannot resolve link to sec from text:
	...{sec}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb':2: Cannot resolve link to project_id from text:
	...{project_id}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb':2: Cannot resolve link to project_id from text:
	...{project_id}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb':2: Cannot resolve link to project_id from text:
	...{project_id}...
[warn]: In file `lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb':2: Cannot resolve link to project_id from text:
	...{project_id}...
```

### PR DESCRIPTION
**Pull request by blowmage**
This PR resolves the remaining Logging warnings and enables CI failure when a documentation warning is introduced.

[closes #2308]

### CODE REVIEW

File: google-cloud-logging/lib/google/cloud/logging/rails.rb [hunk 1]
```diff
@@ -30,8 +30,10 @@ module Logging
       # {Google::Cloud::Logging::Logger} instance to be used by the Rails
       # application.
       #
-      # The Middleware is only added when certain conditions are met. See
-      # {use_logging?} for details.
+      # The Middleware is only loaded when certain conditions are met. These
```
Comment (blowmage) [inline google-cloud-logging/lib/google/cloud/logging/rails.rb]: @dazuma What do you think of these changes?

Comment (dazuma) [reply google-cloud-logging/lib/google/cloud/logging/rails.rb]: The `use_logging` configuration values actually override `Rails.env.production?`. That is, `use_logging` set to `false` will disable the middleware regardless of `Rails.env`. So maybe better:

```
The middleware is loaded only when certain conditions are met. These conditions are when the configuration `Google::Cloud.configure.use_logging` (also available as `Rails.application.config.google_cloud.use_logging` for a Rails application) is set to `true`, or, if the configuration is left unset but `Rails.env.production?` is `true`.
```

Comment (blowmage) [reply google-cloud-logging/lib/google/cloud/logging/rails.rb]: That is more clear. Updated. PTAL.
